[DB-16200] Improve explains by making JSON default and adding debug option
Xeograph/ocient_jdbc pull request #130
Opened 2021-04-06 19:26 UTC by jlchen0

2021-04-07 16:11 UTC, ems236 commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +		if (startsWithIgnoreCase(cmd, "EXPLAIN DEBUG"))
I think the space actually matters a bit here because you're trimming the length including the space a few lines later.

2021-04-07 16:11 UTC, ems236 commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +		if (startsWithIgnoreCase(cmd, "EXPLAIN DEBUG"))
It might be good to rewrite these in a way where whitespace doesn't matter anyway. I think Timmy is already looking at something like that for describe table, so check with him.

2021-04-13 01:15 UTC, ems236 approved these changes
Can you also add these changes to release_notes.adoc?
I think db is also on 1.98 now, so bump that to 1.99.

2021-04-13 14:13 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +		}
same here.

2021-04-13 14:15 UTC, tli-ocient requested changes
please check that the spacing is working correctly

2021-04-15 14:12 UTC, tli-ocient approved these changes

2021-04-16 16:34 UTC, merged