[DB-16081] result set support + cache limit warning
Xeograph/ocient_jdbc pull request #132
Opened 2021-04-14 22:23 UTC by tli-ocient

https://ocient.atlassian.net/browse/DB-16081

2021-04-16 15:22 UTC, jasonar81 requested changes

2021-04-16 15:22 UTC, jasonar81 commented on src/main/java/com/ocient/jdbc/XGResultSet.java
> +					// The cachedOrNewStatement will just be thrown out.
Isn't there a way to do this such that when we are done with this, it will go back to the pool?

2021-04-16 15:22 UTC, jasonar81 commented on src/main/java/com/ocient/jdbc/XGResultSet.java
> +		if (done && didFirstFetch.get() && !cacheLimitBreak.get())
Not sure I follow this. One of the key points is that we are not tying up the main user thread and that it can go submit a new query. Does this prevent that?

2021-04-16 19:14 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGResultSet.java
> +					// The cachedOrNewStatement will just be thrown out.
added returning that statement back to the pool

2021-04-16 19:18 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGResultSet.java
> +		if (done && didFirstFetch.get() && !cacheLimitBreak.get())
No, a new query will come with a new result set.And I've tested this on the CLI. After issuing a query that hits the first limit, I can still fire off new queries as the other query finishes asynchronously

2021-04-16 19:31 UTC, jasonar81 approved these changes

2021-04-17 21:00 UTC, jasonar81 approved these changes

2021-04-17 21:00 UTC, merged