User/tli/extract configuration impl
Xeograph/ocient_jdbc pull request #198
Opened 2021-11-08 21:34 UTC by tli-ocient

https://ocient.atlassian.net/browse/SOL-12

Let me know if there are some other unit tests I should add.

2021-11-09 16:24 UTC, cj81499 commented on src/test/java/com/ocient/cli/extract/ExtractConfigurationTest.java
> +    public void test_defaultConfig()
nit, remove `test_` prefix from all tests

2021-11-09 16:38 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        if(!locationType.equals("LOCAL") && !locationType.equals("S3")){
Each of `LOCAL`/`S3`, `DELIMITED`, `NONE`/`GZIP`, and `S3`/`NONE` should be an `enum`. This is especially important b/c it's pretty likely that more options need to be added to each of these in the future (ex, additional compression types).

`EnumUtils` ([docs](https://commons.apache.org/proper/commons-lang/javadocs/api-release/org/apache/commons/lang3/EnumUtils.html)) may be helpful.

2021-11-10 16:14 UTC, tli-ocient commented on src/test/java/com/ocient/cli/extract/ExtractConfigurationTest.java
> +    public void test_defaultConfig()
ok, removed

2021-11-10 16:15 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        if(!locationType.equals("LOCAL") && !locationType.equals("S3")){
good point, changed

2021-11-10 17:48 UTC, dcoombs-ocient requested changes
Mostly LGTM, a few comments.

2021-11-10 17:48 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_BUCKET = "NONE";
Default should be `""`

2021-11-10 17:48 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String AWS_KEY_SECRET = "aws_key_secret";
This should be `aws_secret_key`

2021-11-10 17:48 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +public class ExtractConfiguration {
Can we keep the formatting of this file inline with the formatting of the rest of the driver (braces all on newlines)?

2021-11-10 17:48 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private void validateConfiguration() throws ParseException{
Does this class have access to a logger at all? Could we set that up?

I'd like if this function also logged warnings when we see configuration that will be ignored. For example if you set a `BUCKET` but you are doing a `local` load.

2021-11-10 17:54 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_FILE_TYPE = "DELIMITED";
Does it make more sense for this to be a `FileType` instead of a `String`?

2021-11-10 17:54 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        fileType = FileType.valueOf(config.getString(FILE_TYPE, DEFAULT_FILE_TYPE).toUpperCase());
Thoughts on using [EnumUtils.getEnumIgnoreCase](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/EnumUtils.html#getEnumIgnoreCase-java.lang.Class-java.lang.String-E-)?

2021-11-10 17:54 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_COMPRESSION = "NONE";
`Compression` instead of a `String`?

2021-11-10 17:54 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_COMPRESSION = "NONE";
`Compression` instead of a `String`?

2021-11-10 17:54 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +                Collectors.toUnmodifiableMap(k -> k.toLowerCase(), config::getProperty)
Can we use `String::toLowerCase` instead of `k -> k.toLowerCase()`?

2021-11-10 17:54 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_BUCKET = "NONE";
Why not just use `null`?

2021-11-10 18:01 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_BUCKET = "NONE";
Over `null`?

2021-11-10 18:06 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_BUCKET = "NONE";
`null` is better

2021-11-10 18:13 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_FILE_TYPE = "DELIMITED";
No, this is the value / default value pulled out of properties, which is then converted to an enum.

2021-11-10 18:13 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_COMPRESSION = "NONE";
same as above

2021-11-10 18:19 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_COMPRESSION = "NONE";
same as above

2021-11-10 18:40 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +                Collectors.toUnmodifiableMap(k -> k.toLowerCase(), config::getProperty)
yes

2021-11-10 18:41 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        fileType = FileType.valueOf(config.getString(FILE_TYPE, DEFAULT_FILE_TYPE).toUpperCase());
No, the difference between that and `valueOf` is that instead of throwing, it resolves to a null. I think we want to just throw here so that this fails immediately.

2021-11-10 18:41 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String AWS_KEY_SECRET = "aws_key_secret";
changed

2021-11-10 18:41 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_BUCKET = "NONE";
changed to null

2021-11-10 18:44 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +public class ExtractConfiguration {
I changed it for this file... but the formatting is not consistent throughout the driver anyway. I would rather we not enforce this rule until we decide on a formatter for the driver as a whole. At that point we can apply it to all the files. It's hard for me to manually do this as I am used to typing it out this way (opening braces on the same line).

2021-11-10 18:45 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private void validateConfiguration() throws ParseException{
let me see

2021-11-10 19:08 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private void validateConfiguration() throws ParseException{
added a logger and a warning

2021-11-10 20:48 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        fileType = FileType.valueOf(config.getString(FILE_TYPE, DEFAULT_FILE_TYPE).toUpperCase());
As is, we're still using a String to represent an Enum for `DEFAULT_FILE_TYPE` (and `DEFAULT_COMPRESSION`).

If we change the type of `DEFAULT_FILE_TYPE` to `FileType`, we can use `getEnumIgnoreCase` with a `defaultEnum` argument. The code would look like:

```java
fileType = EnumUtils.getEnumIgnoreCase(FileType.class, config.getString(FILE_TYPE), DEFAULT_FILE_TYPE);
```

If you want to be consistent and use `getEnumIgnoreCase` for all of these, `notNull` returns the argument you pass it, so we can wrap the one used to get `locationType` with `notNull` like so:

```java
locationType  = notNull(EnumUtils.getEnumIgnoreCase(LocationType.class, config.getString(LOCATION_TYPE)), "Location type is a required configuration option");
```

but I'm also perfectly content sticking w/ `Enum.valueOf` for it, because there is no default.

2021-11-10 20:48 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        notNull(locationType, "Location type is a required configuration option");
Reading the  [docs](https://commons.apache.org/proper/commons-configuration/apidocs/index.html), it sounds like `config.getString` can return `null`, so `toUpperCase` could cause a NPE.

On the other hand, `Enum.valueOf` will throw `IllegalArgumentException` "if the specified enum type has no constant with the specified name" ([docs](https://docs.oracle.com/javase/7/docs/api/java/lang/Enum.html#valueOf(java.lang.Class,%20java.lang.String))).

I think `notNull` just needs to be moved to check the result of `config.getString(LOCATION_TYPE)`.

2021-11-10 23:53 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        fileType = FileType.valueOf(config.getString(FILE_TYPE, DEFAULT_FILE_TYPE).toUpperCase());
Maybe I am misunderstanding you.
I think doing this for `fileType`:
`fileType = EnumUtils.getEnumIgnoreCase(FileType.class, config.getString(FILE_TYPE), DEFAULT_FILE_TYPE);
`
would result in getting the default (DELIMITED), if they ever specify something incorrect (`file_type="badThing"`), rather than erroring loudly which is what I want.

If I do it without the default argument,
`fileType = EnumUtils.getEnumIgnoreCase(FileType.class, config.getString(FILE_TYPE));`
then that would result in null if `file_type` is unspecified because `config.getString(FILE_TYPE)` would return null

2021-11-10 23:57 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        notNull(locationType, "Location type is a required configuration option");
Good point. changed.

2021-11-11 16:52 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +public class ExtractConfiguration {
I didn't realize that the code was mixed-mode on this already. That's fine, we will add a formatter in the future, but for now you can chose whatever format you want for new files. For existing files try and keep the same mode if possible.

2021-11-11 17:02 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        fileType = FileType.valueOf(config.getString(FILE_TYPE, DEFAULT_FILE_TYPE).toUpperCase());
I definitely think we want to catch something like `file_type="bad_thing"`. `EnumUtils.getEnumIgnoreCase` with a default hides that, so we shouldn't use it.

Lets stick with the code as is. However, we should catch the exceptions thrown by `Enum.valueOf` (looks like `IllegalArgumentException` and `NullPointerException`) and wrap them in a `ParseException` such that the user of this constructor only needs to catch `ParseException`.

2021-11-11 18:29 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +        fileType = FileType.valueOf(config.getString(FILE_TYPE, DEFAULT_FILE_TYPE).toUpperCase());
done

2021-11-11 18:57 UTC, dcoombs-ocient approved these changes

2021-11-11 18:57 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_COMPRESSION = "NONE";
Rather than hardcoding the String, can we get it from `Compression.NONE.toString()`?

It's unlikely, but that way if `NONE` is no longer a valid compression type in the future, the compiler will yell at us. The same applies to `DEFAULT_FILE_TYPE`

2021-11-11 19:01 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +            maxRowsPerFile = config.getInt(MAX_ROWS_PER_FILE, DEFAULT_MAX_ROWS_PER_FILE);
possible conversion error. `geInt("Abcd")`

2021-11-11 19:03 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_COMPRESSION = "NONE";
yes, changed

2021-11-11 19:06 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +            maxRowsPerFile = config.getInt(MAX_ROWS_PER_FILE, DEFAULT_MAX_ROWS_PER_FILE);
Makes sense. It looks like `getBoolean` (for `skipHeader`) can too ([docs](https://commons.apache.org/proper/commons-configuration/javadocs/v1.10/apidocs/org/apache/commons/configuration/Configuration.html#getBoolean(java.lang.String))), so we ought to move it.

2021-11-11 19:09 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +            maxRowsPerFile = config.getInt(MAX_ROWS_PER_FILE, DEFAULT_MAX_ROWS_PER_FILE);
done, thanks

2021-11-11 19:09 UTC, cj81499 approved these changes
LGTM!

2021-11-11 19:09 UTC, merged