User/tli/byte array wrapper and binary format
Xeograph/ocient_jdbc pull request #203
Opened 2021-11-18 22:00 UTC by tli-ocient

https://ocient.atlassian.net/browse/SOL-16
https://ocient.atlassian.net/browse/SOL-19

2021-11-18 22:03 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGByteArrayHelper.java
> +    }
This utility function was written before my time. I see other utilities that does bytes to hex conversion for us that we could just replace this with. I decided against it since this is used in the driver in a few places and I didn't want to change it in case there is some speed concerns.

2021-11-18 22:05 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ByteArrayWrapper.java
> +                return  "0x" + XGByteArrayHelper.bytesToHex(byteArray);
would it be better to case hexadecimal and default throw?

2021-11-22 22:14 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ByteArrayWrapper.java
> +                return  "0x" + XGByteArrayHelper.bytesToHex(byteArray);
A case for hex and default throw would be better imo. As is, if we add another `BinaryFormat` in the future, this code would (try to) use the hex format, rather than failing, which would direct a developer's attention to a place where additional logic is needed.

Depending on which version of Java this targets, we could use a [`switch` expression](https://docs.oracle.com/en/java/javase/17/language/switch-expressions.html) instead, and the compiler would check that all possible cases are covered.

The only other solution I can think of would be to make `ByteArrayWrapper` an interface, and use a factory to get an instance based on the format (ex: `Base64ByteArrayWrapper`). That way, the individual classes would only be responsible for logic specific to the associated `BinaryFormat`.

Given this class is as simple as it is today, a factory seems like overkill for now, but if you expect this class to become more complex, it could be a worthwhile choice. I don't know enough to make a prediction about how this code will change/grow over time, so I trust your judgement either way.

2021-11-22 22:14 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ResultSetExtractor.java
>              } else if (element instanceof byte[]){
not sure what version of java we target, but potentially possible to use [pattern matching on `instanceof`](https://docs.oracle.com/en/java/javase/17/language/pattern-matching-instanceof-operator.html)

2021-11-22 22:14 UTC, cj81499 commented on src/test/java/com/ocient/cli/extract/RecordExtractorFactoryTest.java
> +            row.add(new String("deadbeef").getBytes(Charset.defaultCharset())); // This tests the byte array wrapper.
no need for `new String`. `"deadbeef"` is already a `String`.

2021-11-23 04:17 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGTimestamp.java
> +		}
spotbugs called us out on this: https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#stcal-call-to-static-dateformat-stcal-invoke-on-static-date-format-instance
I added a synchronized keyword to get it to keep quiet. While moving this out into a static member does increase single threaded performance, if spotbugs is right and we have to synchronize on this, then it will limit our future multithread performance (since one thread can be in there at a time).

2021-11-23 04:18 UTC, tli-ocient commented on src/test/java/com/ocient/cli/extract/RecordExtractorFactoryTest.java
> +            row.add(new String("deadbeef").getBytes(Charset.defaultCharset())); // This tests the byte array wrapper.
changed

2021-11-23 04:18 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ResultSetExtractor.java
>              } else if (element instanceof byte[]){
i think our minimum version requirements for jdbc is java 11

2021-11-23 04:18 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ByteArrayWrapper.java
> +    final private BinaryFormat binaryFormat;
done

2021-11-23 04:18 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ByteArrayWrapper.java
> +                return  "0x" + XGByteArrayHelper.bytesToHex(byteArray);
yea i agree, changed

2021-11-23 20:14 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ByteArrayWrapper.java
> +        switch(binaryFormat){
This may be a premature optimization, but since the `binaryFormat` is known at the time where we create the `ByteArrayWrapper` we could make a `ByteArrayWrapperFactory` that does this switch at construction and not at runtime.

I think this is okay to leave for now. We will probably get some branch prediction that will make the performance impact negligible.

2021-11-23 20:18 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ByteArrayWrapper.java
> +                throw new IllegalArgumentException(String.format("Invalid binary format specified: %s", binaryFormat.toString()));
Can you do this check in the constructor? I'd like to know that there is an invalid binary format at construction. 

You'll probably have to leave this check here to make the compiler happy, but we should catch this in the constructor.

2021-11-23 20:19 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ResultSetExtractor.java
>              } else if (element instanceof byte[]){
We will be on Java 11 for the foreseeable future since this is a client-side jar (not everyone is up to speed on their java versions).

2021-11-23 20:19 UTC, dcoombs-ocient commented on src/main/java/com/ocient/jdbc/XGByteArrayHelper.java
> +    }
Thats fine with me.

2021-11-23 20:22 UTC, dcoombs-ocient commented on src/main/java/com/ocient/jdbc/XGTimestamp.java
> +		}
Well that's annoying. This might be why the code wasn't written like this in the first place.

What about using `ThreadLocal<T>` https://stackoverflow.com/questions/16249687/java-threadlocal-static?

2021-11-23 21:08 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ByteArrayWrapper.java
> +        switch(binaryFormat){
I think you're discussing the same thing I brought up here: https://github.com/Xeograph/ocient_jdbc/pull/203#discussion_r754672365

2021-11-23 21:10 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ByteArrayWrapper.java
> +                throw new IllegalArgumentException(String.format("Invalid binary format specified: %s", binaryFormat.toString()));
imo, this is probably the strongest reason to refactor to a use a `ByteArrayWrapperFactory` now, rather than waiting.

2021-11-24 02:05 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGTimestamp.java
> +		}
This is pretty neat. I was worried we'd have to implement something like this. I moved construction of the SDF back to inside of toString, since we want each thread to execute it once.

2021-11-24 05:56 UTC, cj81499 requested changes

2021-11-24 05:56 UTC, cj81499 commented on src/main/java/com/ocient/jdbc/XGTime.java
> +		return threadLocalSDF.get().format(this) + "." + String.format("%09d", getNanos());
I don't think this logic is quite correct because it's possible that multiple threads could get `null`, create `sdf`, and call `set` on `threadLocalSDF`.

I don't have any prior experience with `ThreadLocal` in Java, but the [docs](https://docs.oracle.com/javase/7/docs/api/java/lang/ThreadLocal.html) make it sound like the intended approach is to extend it, overrideing the `initialValue` method to construct and return the value you want to be thread local.

2021-11-24 06:31 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGTime.java
> +		return threadLocalSDF.get().format(this) + "." + String.format("%09d", getNanos());
I'm not familiar with this class either. 
` it's possible that multiple threads could get null, create sdf, and call set on threadLocalSDF`
My impression was that this was a map with the read as a key to the value. Thus the multiple threads would be getting "different" nulls and then setting `threadLocalSDF` for different keys.

Regardless, I was doing something else wrong. We cannot initialize the initial value to be null like I was doing or else it would throw a null exception. We don't need to do that anyway. We can just set it to be exactly what want by overriding initial value like you said. I think this is correct now.

2021-11-24 16:24 UTC, dcoombs-ocient commented on src/main/java/com/ocient/jdbc/XGTime.java
> +		return threadLocalSDF.get().format(this) + "." + String.format("%09d", getNanos());
Looks good now.

2021-11-24 16:24 UTC, dcoombs-ocient approved these changes

2021-11-24 17:35 UTC, cj81499 approved these changes
One last concern, otherwise LGTM.

2021-11-24 17:35 UTC, cj81499 commented on src/main/java/com/ocient/jdbc/XGTime.java
> +	private static ThreadLocal<SimpleDateFormat> threadLocalSDF = new ThreadLocal<SimpleDateFormat>(){
Since this and the `ThreadLocal` in `XGTimestamp.java` are identical, except for the date format string, do you think it's worth refactoring into a class that takes a date format string parameter?

2021-11-24 17:57 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGTime.java
> +	private static ThreadLocal<SimpleDateFormat> threadLocalSDF = new ThreadLocal<SimpleDateFormat>(){
We might even want to refactor some of the other toString methods in these classes (There's more than just toString), but I don't want to do that right now

2021-11-24 17:57 UTC, merged