User/tli/more extract config
Xeograph/ocient_jdbc pull request #204
Opened 2021-11-18 22:24 UTC by tli-ocient

https://ocient.atlassian.net/browse/SOL-19

2021-11-18 22:26 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private char getCharFromConfigHelper(ImmutableConfiguration config, final String key, final char defaultChar) throws ParseException
Definitely open to suggestions on how to do this better if possible. The problem is there isn't a getChar from ImmutableConfiguration (Configuration). So I rely on taking a 1 length string.

2021-11-18 22:27 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private char getCharFromConfigHelper(ImmutableConfiguration config, final String key, final char defaultChar) throws ParseException
Univocity parser takes chars for quote and quoteEscape options

2021-11-22 16:31 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private char getCharFromConfigHelper(ImmutableConfiguration config, final String key, final char defaultChar) throws ParseException
The generic get method might work? If not, this seems fine to me.

https://commons.apache.org/proper/commons-configuration/apidocs/org/apache/commons/configuration2/ImmutableConfiguration.html#get-java.lang.Class-java.lang.String-T-

2021-11-22 16:31 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +            encoding = (config.getString(ENCODING) != null) ? Charset.forName(config.getString(ENCODING)) : DEFAULT_ENCODING;
Might be clearer to use `Optional`? I mostly like this because it avoids calling `config.getString(ENCODING)` multiple times.

```suggestion
            encoding = Optional.ofNullable(config.getString(ENCODING)).map(Charset::forName).orElse(DEFAULT_ENCODING);
```

2021-11-22 18:30 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +            encoding = (config.getString(ENCODING) != null) ? Charset.forName(config.getString(ENCODING)) : DEFAULT_ENCODING;
ok, changed

2021-11-22 18:31 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private char getCharFromConfigHelper(ImmutableConfiguration config, final String key, final char defaultChar) throws ParseException
this probably won't do it, since I'd have to use `String` as the first argument, since that is what it is when it gets entered by the syntax parser.

2021-11-22 22:30 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private char getCharFromConfigHelper(ImmutableConfiguration config, final String key, final char defaultChar) throws ParseException
I tried the following, and it worked how I expected (how the comments say):


```java
import java.util.Map;
import org.apache.commons.configuration2.MapConfiguration;

class Playground {
  public static void main(final String[] args) {
    final var mc = new MapConfiguration(Map.ofEntries(Map.entry("1", "!"), Map.entry("2", "oops")));

    // prints "!"
    final var c1 = mc.get(Character.class, "1");
    System.out.println(c1);

    // throws org.apache.commons.configuration2.ex.ConversionException
    final var c2 = mc.get(Character.class, "2");
    System.out.println(c2);
  }
}
```

2021-11-23 02:45 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private char getCharFromConfigHelper(ImmutableConfiguration config, final String key, final char defaultChar) throws ParseException
thanks, that just works

2021-11-23 20:11 UTC, dcoombs-ocient approved these changes

2021-11-23 21:03 UTC, cj81499 requested changes

2021-11-23 21:03 UTC, cj81499 commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private final Character escape;
this can still be a `char`. Java will auto unbox the `Character` for us. https://docs.oracle.com/javase/tutorial/java/data/autoboxing.html

2021-11-24 00:24 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private final Character escape;
Yea I noticed this in `RecordExtractorFactory.java` where I didn't need to convert it myself. This is pretty neat. I am going to keep it this way since Dan had said it was more Java like to use Integer rather than int for max rows.

2021-11-24 00:25 UTC, merged

2021-11-24 00:30 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private final Character escape;
I said that in the use case where the configuration variable could be `null`. I don't think this one can ever be `null`? In that case its better to use a `char` over a `Character`.

2021-11-24 00:33 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private final Character escape;
Ah ok, I'll switch this.

2021-11-24 00:46 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    private final Character escape;
https://github.com/Xeograph/ocient_jdbc/pull/207