[SOL-17] User/tli/s3 output stream
Xeograph/ocient_jdbc pull request #208
Opened 2021-11-30 21:12 UTC by tli-ocient

https://ocient.atlassian.net/browse/SOL-17

2021-11-30 21:19 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_REGION = null;
Should region have a default?

2021-11-30 21:20 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        }
Should we require that both be specified or neither?

2021-11-30 21:40 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +    public synchronized void flush(){
There is a rule stated here: https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPart.html
that each part, except the last, needs to be 5MB.
This isn't a problem now since we are the only ones using this class. However, if we were to give it to someone else, there could be a situation where they open this stream, write a tiny amount, flush, write another tiny amount, and flush again.

This will break that rule and result in an exception being thrown stating
`Your proposed upload is smaller than the minimum allowed size`.

We could change this `flush` to do nothing, and add a `flushInternal` method which does what this does. Then call `flushInternal` everywhere we need it in this file. Of course then `flush` would not actually synchronize the bytes when they call it. Thoughts?

2021-12-01 15:32 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_REGION = null;
In the LAT we defaulted to "us-east-2" https://ocient.gitlab.io/lat/userguide.html#_s3_source_specific_configuration

2021-12-01 15:33 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        }
Yeah that sound like a good lint.

2021-12-01 15:36 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +    public synchronized void flush(){
I think we should have this `flush` do nothing and clearly state that in the comment. Basically, for this output stream, nobody should be calling flush and should only use `close()` when complete.

2021-12-01 15:38 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/CLI.java
> +		catch (IllegalStateException | IllegalArgumentException | IOException | SQLException | SdkClientException e)
I don't think our interface should leak the `SdkClientException`, you should catch that somewhere else and wrap it into one of the other exceptions here, probably `IOException`.

2021-12-01 15:41 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
What about for Anonymous access (when there are no keys specified)?

2021-12-01 15:42 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        builder.setPathStyleAccessEnabled(extractConfig.getPathStyleAccess());
Any reason this is split into its own line statement? Can it just be added to the previous?

2021-12-01 15:42 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        AmazonS3 s3Client = builder.build();
Same here.

2021-12-01 15:44 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +                outputStream = makeS3OutputStream(fileName);
Just noting this so we don't forget, this may need to be proved out in testing.

I don't think we want to wrap this `outputStream` in a `BufferedWriter` (like you do below), because the `S3OutpoutStream` already buffers. We should make a ticket to test this out. If the performance is better (or the same, since it uses less memory) we should remove the `BufferedWriter`.

2021-12-01 15:50 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +    public void write(byte[] byteArray){
TIL: https://docs.oracle.com/javase/7/docs/api/java/io/OutputStream.html#write(byte[])

Interesting they would design their API like that. I would have expected it to act like a stream and append rows to the next offset...

2021-12-01 15:53 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +        UploadPartResult uploadResult = s3Client.uploadPart(new UploadPartRequest()
What exceptions does this throw? We probably want to catch them and adhere to the `write()` interface contract and re-throw an `IOException`

2021-12-01 15:55 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +public class S3OutputStream extends OutputStream{
The logic here LGTM. I think we should try and get some tests written for this class using a mock `s3Client`.

@rveitch-Ocient @cj81499 @ejiang-Ocient @zzpxyx, I'm not super well versed in Java mocks, can one of you point Timmy to examples in the LAT codebase?

2021-12-01 15:55 UTC, dcoombs-ocient requested changes
Mostly LGTM, a few small comments. I'd like to get some tests added if possible.

2021-12-01 16:02 UTC, zzpxyx commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +public class S3OutputStream extends OutputStream{
In LAT, we are using JUnit plus Mockito. We just mock an S3 client as any other mocked objects: https://gitlab.com/ocient/lat/-/blob/main/src/test/java/com/ocient/lat/source/file/s3/S3FileFetcherTest.java#L44.

2021-12-01 16:04 UTC, zzpxyx commented on pom.xml
> +        <version>1.12.119</version>
Just curious, any reason to use the V1 AWS Java SDK as opposed to [V2](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html)?

2021-12-01 16:25 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        builder.setPathStyleAccessEnabled(extractConfig.getPathStyleAccess());
combined

2021-12-01 16:25 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        AmazonS3 s3Client = builder.build();
combined, I missed that there was a `withPathStyleAccessEnabled` as well. Was using `setPathStyleAccessEnabled` which returns void and could not chain.

2021-12-01 16:29 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
I am not sure what you mean. When neither keys are specified, the default provider chain is used above to find them

2021-12-01 16:31 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
well I should say, they are always found by the default provider chain and overwritten if the user specifies anything. I should probably change this to only look with the default provider chain if the user doesn't specify.

2021-12-01 16:54 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
What do you mean "always found by the default provider chain"? What does it do if it can't find credentials anywhere? https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.html

2021-12-01 17:03 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
Sorry not "always found". If it is not found then, looking at their code, an exception is thrown.
`
        throw new SdkClientException("Unable to load AWS credentials from any provider in the chain: "
                                     + exceptionMessages);
`

2021-12-01 17:04 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
This is what I mean by "anonymous access" not all S3 implementations need keys (COS in riverside for example should be setup for "anonymous access").

2021-12-01 17:09 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
To summarize, they need to be able to write to the server even if the no credentials are found if the server allows for anonymous access?

2021-12-01 17:12 UTC, dcoombs-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(awsAccessKey, awsSecretKey);
Correct

2021-12-01 18:43 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/ExtractConfiguration.java
> +    public static final String DEFAULT_REGION = null;
region now defaults to "us-east-2"

2021-12-01 18:43 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/RecordExtractorFactory.java
> +        }
ExtractConfiguration now requires that both are specified or neither. This now proceeds with that assumption

2021-12-01 18:45 UTC, rveitch-Ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +public class S3OutputStream extends OutputStream{
In addition to `mock()`, `spy()` is also good to know about for when you want to use a real implementation but override a particular method for your test. Useful when the test orchestration is complex and you'd rather drive most of it with the real code rather than mocking a complex set of behaviors to mirror what the real code would do.

2021-12-01 18:46 UTC, rveitch-Ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +public class S3OutputStream extends OutputStream{
mockito docs: https://site.mockito.org/

2021-12-01 18:57 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +    public synchronized void flush(){
moved logic out into a `flushInternal` method which is now used. `flush` now does nothing.

2021-12-01 18:58 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +public class S3OutputStream extends OutputStream{
thanks, I will take a look at this and add some mock tests

2021-12-01 19:46 UTC, tli-ocient commented on pom.xml
> +        <version>1.12.119</version>
Oh I didn't realize there was a V2.
Is the proper dependency for V2
`    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>s3</artifactId>
      <version>2.17.53</version>
    </dependency>`

I copied this from the LAT project

2021-12-01 19:58 UTC, dcoombs-ocient commented on pom.xml
> +        <version>1.12.119</version>
Yes although you might as well get onto `2.17.93` as it is the latest: https://mvnrepository.com/artifact/software.amazon.awssdk/s3

2021-12-01 20:00 UTC, zzpxyx commented on pom.xml
> +        <version>1.12.119</version>
According to the V2 doc, it's `2.17.93` at the moment: https://github.com/aws/aws-sdk-java-v2#using-the-sdk. Note that V1 and V2 may have some slight difference in API naming, packaging, and usage. If we are in a hurry, using V1 is OK-ish since it's not fully deprecated. If we have time, I'd recommend converting it to the future-proofing V2.

2021-12-01 20:02 UTC, tli-ocient commented on pom.xml
> +        <version>1.12.119</version>
We have time. Theres not too much to convert, I'll do this now

2021-12-01 20:14 UTC, tli-ocient commented on src/main/java/com/ocient/cli/CLI.java
> +		catch (IllegalStateException | IllegalArgumentException | IOException | SQLException | SdkClientException e)
wrapped it all instances that throw SdkClientException in IOException for `S3OutputStream.java`

2021-12-01 20:14 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +        UploadPartResult uploadResult = s3Client.uploadPart(new UploadPartRequest()
wrapped

2021-12-02 03:35 UTC, tli-ocient commented on pom.xml
> +        <version>1.12.119</version>
Changed to using V2. Most of it is pretty straightforward, though I do have one question for @zzpxyx . Do you know what `DefaultCredentialsProvider.create()` does if it cannot find the default credentials set up anywhere? The equivalent of this in V1 throws an exception, but this looks it doesn't. So how does this behave if no credentials is not set up anywhere in this list:
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/DefaultCredentialsProvider.html

2021-12-02 15:31 UTC, zzpxyx commented on pom.xml
> +        <version>1.12.119</version>
Looking at the source code, I think it will throw an exception, no? https://github.com/aws/aws-sdk-java-v2/blob/4289e9a98c8db6b25643c40c9e77fdae6af1d5d5/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsCredentialsProviderChain.java#L109

2021-12-02 15:42 UTC, tli-ocient commented on pom.xml
> +        <version>1.12.119</version>
Ok, thanks, I missed that. This should all be fine then.

2021-12-02 22:05 UTC, tli-ocient commented on src/main/java/com/ocient/cli/extract/S3OutputStream.java
> +public class S3OutputStream extends OutputStream{
added mock tests

2021-12-03 15:58 UTC, merged