[DB-19576]: Added new columns in system queries
Xeograph/ocient_jdbc pull request #237
Opened 2022-03-11 22:39 UTC by susmita-saha

* sys.queries: initial_priority, initial_effective_priority, effective_priority, priority_adjust_factor, priority_adjust_time
* sys.completed_queries: initial_priority, initial_effective_priority, final_effective_priority, priority_adjust_factor, priority_adjust_time

2022-03-11 22:39 UTC, susmita-saha commented on src/main/java/com/ocient/cli/CLI.java
> +				row.getEffectivePriority(), row.getInitialPriority(), row.getInitialEffectivePriority(), row.getEstimatedTimeSec(), row.getElapsedTimeSec(),
I don't this function being used anywhere.

2022-03-14 14:19 UTC, tli-ocient requested changes

2022-03-14 14:19 UTC, tli-ocient commented on src/main/proto/ClientWireProtocol.proto
> +	float effective_priority = 2;
You cannot change the member name of protos. This will break backwards compatibility

2022-03-14 14:19 UTC, tli-ocient commented on src/main/proto/ClientWireProtocol.proto
> +	double final_effective_priority = 16;           // the final effective dynamically adjusted priority
Same here, cannot be changed.

2022-03-14 14:19 UTC, tli-ocient commented on src/main/java/com/ocient/cli/CLI.java
> +				row.getEffectivePriority(), row.getInitialPriority(), row.getInitialEffectivePriority(), row.getEstimatedTimeSec(), row.getElapsedTimeSec(),
Like you said, you shouldn't need to change this to have your new columns be reflected. Did you test it? The new columns should automatically be reflected once you change the protos.

2022-03-14 14:19 UTC, tli-ocient commented on src/main/java/com/ocient/cli/CLI.java
> +				row.getEffectivePriority(), row.getInitialPriority(), row.getInitialEffectivePriority(), row.getEstimatedTimeSec(), row.getElapsedTimeSec(),
In fact, please delete this function.

2022-03-14 16:56 UTC, susmita-saha commented on src/main/proto/ClientWireProtocol.proto
> +	float effective_priority = 2;
I think it is okay to rename the fields, as long as I am not changing the type and position.
It shouldn't break backward compatibility.

2022-03-14 16:58 UTC, susmita-saha commented on src/main/java/com/ocient/cli/CLI.java
> +				row.getEffectivePriority(), row.getInitialPriority(), row.getInitialEffectivePriority(), row.getEstimatedTimeSec(), row.getElapsedTimeSec(),
Yes, I tested it, and the new columns show up in result set.

2022-03-14 17:14 UTC, tli-ocient approved these changes

2022-03-14 17:14 UTC, merged