[DB-20111] implement setObject() with the targetSqlType param
Xeograph/ocient_jdbc pull request #252
Opened 2022-05-10 18:03 UTC by jwilliams-ocient

2022-05-11 18:17 UTC, jasonar81 requested changes

2022-05-11 18:17 UTC, jasonar81 commented on src/main/java/com/ocient/jdbc/XGPreparedStatement.java
> +		// The given timestamp is in UTC. Find the offset needed to represent
If its adding the offset in the getter, it needs to be subtracting the offset here. I think it adds in the getter.
The comment also seems wrong.
I believe this function is given a timestamp in Cal, convert it to whatever the database uses (UTC).
Unless you are reading javadocs that say otherwise...

2022-05-11 18:17 UTC, jasonar81 commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +								final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss.SSS");
And where is the timestamp version, LocalDateTime or whatever its called?

2022-05-11 21:41 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGPreparedStatement.java
> +		// The given timestamp is in UTC. Find the offset needed to represent
Yea, you're right on both counts here. Going to rerun the Metabase tests, I'm not sure how this didn't cause one of them to fail

2022-05-11 21:42 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +								final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss.SSS");
Metabase didn't require it so I didn't add, but it's super trivial, will add support for those types too

2022-05-12 12:28 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +								final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss.SSS");
> Is that all the precision a LocalTime has? 

I just copied the existing format string for `Timestamp` which has millisecond precision. Do we want microsecond precision here? If so should we update the formatter for `Timestamp` too?

2022-05-12 12:30 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +								final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss.SSS");
```suggestion
								final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss.SSSSSS");
```

2022-05-31 16:54 UTC, merged