feat: rewrite XGConnection#reconnect asynchronously [DB-23682]
Xeograph/ocient_jdbc pull request #336
Opened 2023-04-04 21:28 UTC by awang-ocient

2023-04-05 21:22 UTC, awang-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +
I plan to change these blocking class to utilize `CompletableFutures.blockingGet()`

2023-04-05 21:23 UTC, awang-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +		return 1;
Not sure what value to return here?

2023-04-05 21:24 UTC, awang-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +			return conn.setParallelism(parallelism, reset).toCompletableFuture().get();
I plan to change these blocking class to utilize `CompletableFutures.blockingGet()`

2023-04-05 22:16 UTC, jwilliams-ocient requested changes
Mostly minor issues, happy to discuss via huddle zoom if that works best for you 👍🏾

2023-04-05 22:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +						return sendParameterMessage(param).thenApply(confirmationReponse -> 0);
Recursion here can be tricky, there's a possibility we hit a stack overflow when futures complete on the calling thread. We may need to unroll this. Can you add a comment for me to look at this?
```suggestion
                                                FIXME Do we need to unroll the stack here? 
						return sendParameterMessage(param).thenApply(confirmationReponse -> 0);
```

2023-04-05 22:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		try {
wow I think the Result API will clean up the exception handling nicely here...

2023-04-05 22:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		CompletionStage<Void> setPsoCompletionStage = null;
(nit)

I typically avoid nulls if possible, and if something can legitimately be nullable, I'll leave an indicator in the variable name. In this case, the asynchronous execution does not produce a result so what you really want a way to say there is nothing to do.
```suggestion
		CompletionStage<Void> setPsoCompletionStage = StageSupport.voidStage();
```
This way, you can get rid of the null check and always return `setPsoCompletionStage`.

Just a little defensive programming trick.

2023-04-05 22:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
>  				setSchema(schema);
I'm glossing over the exceptional paths (sigh)

```suggestion
		return resetSchema()
		    .map(this::setSchemaAsync)
		    .orElseGet(StageSupport::voidStage)
		    .thenCompose(schemaUpdated -> {
		        if (setPso.isPresent()) {
 			        if (setPso.getAsLong() == -1)
 			        {
 				        // We have to turn it off
 				        return setPSO(false);
 			        }
 			        else if (setPso.getAsLong() > 0)
 			        {
 				        // Set non-default threshold
 				        return setPSO(setPso.getAsLong());
 			        }
 		        }
 		        
 		        // nothing more to do
 		        return StageSupport.voidStage();
		    });
```

2023-04-05 22:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		});
this method now returns a future, so you'd want to "chain" _this_ stage onto the completion of the previous stage `clientHandshakeCompletionStage` using composition, i.e. `thenCompose(...)`. 
```suggestion
		return clientHandshakeCompletionStage.thenCompose(this::clientHandshakeFinalize);
```

2023-04-06 23:56 UTC, awang-ocient commented
> Mostly minor issues, happy to discuss via huddle zoom if that works best for you 👍🏾

I think I resolved all the comments

2023-04-12 15:12 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			completionStage = completionStage.thenCompose(v -> {
There's a subtle distinction between the `thenCompose` and `thenComposeAsync` methods I'd like to take the opportunity to call attention to:

- `thenCompose()`: Returns a new CompletionStage that, when this stage completes normally, is executed with this stage as the argument to the supplied function.
- `thenComposeAsync()`: Returns a new CompletionStage that, when this stage completes normally, is executed using this stage's default asynchronous execution facility, with this stage as the argument to the supplied function.
 
In this case, we want to use the latter to avoid a deadlock situation. A general rule of thumb is to fire callbacks that execute synchronous, blocking code on a separate thread from the one on which the callback is being fired. 

This is extremely non-trivial stuff and dips into the finer implementation details of the `CompletableFuture` library, but it's a great exercise. Take a look when you get a chance! https://www.hackerrank.com/codepair/ymflrslcdzzgujhzkwvzhxvjbxaqzlwx/questions/1?b=eyJpbnRlcnZpZXdfaWQiOjQwNTMwMTQsInJvbGUiOiJpbnRlcnZpZXdlciIsInNob3J0X3VybCI6Imh0dHBzOi8vaHIuZ3MvYTE0MmI0NyIsImNhbmRpZGF0ZV91cmwiOiJodHRwczovL2hyLmdzL2Q0MGI2NmYifQ

2023-04-12 15:12 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		return rowsModifiedCompletionStage.thenApply(rowsModified -> {
(uber nit):

```suggestion
		return sendParameterMessage(builder.build()).thenApply(rowsModified -> {
```

2023-04-12 15:13 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		return rowsModifiedCompletionStage.thenApply(rowsModified -> {
(uber nit):

```suggestion
		return sendParameterMessage(builder.build()).thenApply(rowsModified -> {
```

2023-04-12 15:13 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		return rowsModifiedCompletionStage.thenApply(rowsModified -> {
(uber nit): same here

2023-04-12 15:17 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			return completionStage.thenAccept(Response -> {});
(nit):

Prefer `thenApply()` to convey mapping from `T` => `U`. In this case `U` happens to be `Void` so the net effect is mostly the same, but the intent is much clearer when using `thenApply(...)`.
```suggestion
			return sendRequestWithStandardResponse(wrapper).thenApply(ign -> null);
```

2023-04-12 15:17 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			return completionStage.thenAccept(response -> {});
(nit)

same here RE `thenApply`

2023-04-12 15:18 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
>  			this.priority = null;
The logic below is intended to be executed _after_ `sendParameterMessage` succeeds

2023-04-12 15:18 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
>  		if(reset){
same here, this needs to be done after `sendParameterMessage()` completes successfully

2023-04-12 15:19 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
>  		if(reset){
same here, this needs to be done after `sendParameterMessage()` completes successfully

2023-04-12 15:19 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
>  			this.maxRows = null;
same here, this needs to be done after `sendParameterMessage()` completes successfully

2023-04-12 15:19 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
>  			this.parallelism = null;
same here, this needs to be done after `sendParameterMessage()` completes successfully

2023-04-12 15:19 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> -			}
I think we still need this

2023-04-12 15:20 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			completionStage = response.thenAccept(res -> {});
(nit)

```suggestion
			return sendRequestWithStandardResponse(wrapper).thenApply(ign -> null);
```

2023-04-12 15:21 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			return completionStage.thenApply(confirmationReponse -> 0);
I wonder why we return 0 here at all?

2023-04-12 15:24 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		List<CompletionStage<?>> completionStages = new ArrayList<>();
Unfortunately, this approach won't work because it fires param requests in parallel, when they actually need to be executed serially due to the simplex nature of the protocol. One day soon, I hope to be able to do this - full duplex protocol is on the roadmap, but likely not until like v25

2023-04-12 15:24 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +					LOGGER.log(Level.WARNING, String.format("Exception %s occurred in clientHandshakeFinalize() with message %s", e.toString(), e.getMessage()));
Need to propagate the exception here

2023-04-12 15:24 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +						} catch (Exception e) {}
need to propagate the exception here

2023-04-12 15:25 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		    .thenCompose(schemaUpdated -> {
Might need to handle the error here

2023-04-12 20:54 UTC, awang-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		    .thenCompose(schemaUpdated -> {
Not sure which line you're referencing here?

2023-04-12 20:55 UTC, awang-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			return completionStage.thenApply(confirmationReponse -> 0);
I believe the previous synchronous version of the function also returned 0. TBH I didn't look into the reasoning. Maybe we can return `CompletionStage<Void>` instead?

2023-04-12 20:59 UTC, awang-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> -			}
The previous try block called `getStandardResponse` which throws Exception. The current try block calls `sendRequestWithStandardResponse` which throws IOException but not SQLException.

I don't think it will compile if we try to catch SQLException. Thoughts here? Should `sendRequestWithStandardResponse` throw SQLException?

2023-04-12 23:02 UTC, awang-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			completionStage = completionStage.thenCompose(v -> {
I changed it to `thenComposeAsync` for now, but actually `sendSetSchema()` doesn't appear to be blocking? It returns CompletionStage<Void>

2023-04-18 17:59 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		return allStages.thenAccept(r -> {});
(nit)

This is super clever! Love this approach. 

This is a good opportunity to highlight the `AsyncIterator` interface which provides some syntactic sugar for something like this.

```suggestion
		// Supplier instead of Callable so we don't have to handle the exception on the synchronous interface
                return AsyncIterator
                    .toIterator(setParameterSuppliers)
                    .thenCompose(Supplier::get)
                    
                    // Returns a CompletionStage<List<SQLResult<Void>>> so the caller can decide what to do if any tasks failed
                    .collect(Collectors.toList());
```

2023-04-18 17:59 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			return completionStage.thenApply(confirmationReponse -> 0);
yea idk, either, maybe leave it and add TODO to figure out what the legacy impl was trying to do

2023-04-18 17:59 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		catch (final Exception ex)
So the `feature/nio` branch now removes this exceptional path from the `sendRequest(...)` interface. If the request fails exceptionally, the underlying `TransportException` in the `TransportResult<?>` will indicate whether the request failed on send or recv. Special recovery logic can be added for either case, if necessary.

2023-04-18 17:59 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +	private CompletionStage<Void> sendSetSchema(final String schema) throws Exception
Can return a `SQLResult` now and remove the exception from the method signature
```suggestion
	private CompletionStage<SQLResult<Void>> sendSetSchema(final String schema)
```

2023-04-18 17:59 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> -			}
I see, so I think this is a common pattern in this package:
1. Send request to DB that may complete exceptionally with SQLException
2. If the response contains the `SESSION_EXPIRED_CODE`, refresh the session, then retry the operation.

We can add a `recoverAsync(...)` method to the `*Result` interfaces:
```
/**
 * Maps the error value of this SQLResult to a new completion stage that
 * completes with a new SQLResult by applying the given function. If this 
 * result represents a success, the returned stage will complete with
 * the result.
 *
 * @param fn the function to apply to the error value
 */
default CompletionStage<SQLResult<T>> recover(final Function<? super E, ? extends CompletionStage<SQLResult<T>>> fn) {
    return fold(
        SQLResult::successAsync, 
        fn::apply);
}
```

And then use it here like:
```
sendRequestWithStandardResponse(request)
  .recoverAsync(ex -> {
    if (ex.getErrorCode() == SQLStates.SESSION_EXPIRED.getErrorCode()) {
      return refreshSession()
        .thenCompose(successOrEx -> successOrEx
          .mapSuccessAsync(ign -> sendRequestWithStandardResponse(request)));
    }
    // else
    // propagate the original exception
    return SQLResult.failAsync(ex);
  });
```

2023-04-18 18:07 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		return allStages.thenAccept(r -> {});
```
// Returns a CompletionStage<List<SQLResult<Void>>> so the caller can decide what to do if any tasks failed
// i.e.
whateverThisMethodIs().thenApply(results -> {
  List<SQLResult<Void>> failedResults = results.stream().filter(SQLResult::isException).collect(Collectors.toList());
  if (failedResults.isEmpty()) {
    return SQLResult.voidResult();
  }
  // TODO add suppressed exceptions
  return failedResults.get(0);
});
```

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		return completionStage.thenApply(respOrEx -> respOrEx.isException() ? SQLResult.fail(respOrEx.getException()) : SQLResult.voidResult());
(nit)

This is a good use case for `SQLResult#mapSuccess`, converting `SQLResult<T>` => `SQLResult<U>` where the exception type remains the same. The `Functions::noop` method reference is just syntactic sugar.
```suggestion
		return completionStage.thenApply(respOrEx -> respOrEx.mapSuccess(Functions::noop));
```

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		return sendRequestWithStandardResponse(wrapper, Functions::alwaysTrue)
🔥

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			.thenApply(respOrEx -> respOrEx.isSuccess() ? /* Return 0 on success */ SQLResult.success(0) : SQLResult.fail(respOrEx.getException()));
(nit)

```suggestion
			.thenApply(respOrEx -> respOrEx.mapSuccess(constant(0))));
```

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			if(rowsModifiedOrEx.isSuccess()) {
👍🏾

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		// 	.thenCompose(Supplier::get)
Yep, totally fine to leave this as a TODO, I'm pretty sure your chaining implementation looks fine

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +								closeTransport();
This synchronous call should be issued in a separate thread than the callback via `thenComposeAsync(...)` OR by using the helper method `runAsyncSafe_FIXME(...)`.
```suggestion
								return runAsyncSafe_FIXME(this::closeTransport())
								    .thenApply(constant(successOrEx));
```

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +								closeTransport();
Same here RE: `runAsyncSafe_FIXME(...)`

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +				} catch (SQLException e) {
Should be able to remove this catch block. There's a quite a bit of duplicated log messages in the legacy implementation, I think this is an example of one that can be removed since the caller of `clientHandshakeFinalize` will surely handle the error.

If the log message provided some additional context i.e. failed to set the default schema, iit could provide value but doesn't as is.

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +	public CompletionStage<SQLResult<Void>> setPSO(final boolean on) throws SQLException
```suggestion
	public CompletionStage<SQLResult<Void>> setPSO(final boolean on)
```

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +	public CompletionStage<SQLResult<Void>> setPSO(final long threshold) throws SQLException
```suggestion
	public CompletionStage<SQLResult<Void>> setPSO(final long threshold)
```

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +	public CompletionStage<SQLResult<Integer>> setPriorityAdjustFactor(final Double priorityAdjustFactor, final boolean reset) throws SQLException
```suggestion
	public CompletionStage<SQLResult<Integer>> setPriorityAdjustFactor(final Double priorityAdjustFactor, final boolean reset)
```

2023-04-19 15:54 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +	public void setSchema(final String schema) throws SQLException
`SQLException` stays on this synchronous interface from `java.sql`.

2023-04-19 17:18 UTC, awang-ocient commented
`reconnect()` has a chunk of code which tries to connect to all secondary interfaces in a serial fashion.

https://github.com/Xeograph/ocient_jdbc/blob/4602079730d88ce14f5dcba0e4351031162f575b/src/main/java/com/ocient/jdbc/XGConnection.java#L3542-L3569

The old logic was that if the connect to an interface failed (throws an Exception), then the for loop would continue to the next iteration and try the next interface.

However, because of our async refactor, `clientHandshakeAsync()` no longer throws an Exception, so I believe the for loop terminates after the first iteration because the return statement executes...

How can we work around this? It seems like a different issue because `connect` and `clientHandshakeAsync()` are logically related, but `connect` is blocking whereas `clientHandshakeAsync()` is non-blocking.

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +		return clientHandshakeCompletionStage.thenCompose(v -> clientHandshakeFinalize());
If `clientHandshake(...)` completes exceptionally, I think the returned `CompletionStage<SQLResult<Void>>` will also complete exceptionally, which we actually don't want here. We want to propagate the exception through the `SQLResult` container.
```suggestion
                return runAsync_FIXME(() -> clientHandshake(user, pwd, database, shouldRequestVersion))
                    .thenCompose(successOrEx -> successOrEx
                        .ampSuccessAsync(ign -> clientHandshakeFinalize()));
```

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
>  		forceExternal = force;
Based on the comment above, I think this should be done in the `completionStage.thenApply(...)` block below iff `respOrEx` represents a successful response.

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +							}
(nit)

I think you can remove this check since `successOrEx.getException() instanceof SQLException` will always be true because `SQLResult<T>` is a specialization of `Result<T, SQLException>`.
```suggestion
```

Then you could condense the parent block into:
```java
return clientHandshakeAsync(user, pwd, database, shouldRequestVersion)
    .thenCompose(successOrEx -> successOrEx
       .recoverAsync(ex -> runAsyncSafe_FIXME(this::closeTransport)
           .thenApply(whoCares -> {
             connected = false;
             return successOrEx;
           })));
```

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +					return completionStage;
Does this return change the behavior of this function to fail-fast on the first failed handshake?

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
>  					secondaryIndex = index;
probably want to do this after the future completes

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +					return completionStage;
This will be _very_ hard to write in its current form due to the synchronous control mechanisms (for-loop and exception handling) used by this function.

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +						}
```suggestion
 				        return setPSO(false);
```

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +						}
```suggestion
 				        return setPSO(setPso.getAsLong());
```

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +				}
wondering if we actually want to swallow this exception, I'll have to look at the legacy impl. Sorry we don't have existing unit tests for stuff like this 🤦🏾

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +				return failedResults.get(0);
👍🏾

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +									LOGGER.log(Level.WARNING, String.format("Failed sending set parameter request to the server after refresh with exception %s with message %s", e, e.getMessage()));
(uber nit)

I've been making an effort to clean up some of the logging as I refactor (I know you didn't write it this way).
```suggestion
									LOGGER.log(Level.WARNING, retryOrEx.getException(), () -> String.format("Failed sending set parameter request to the server after refresh: %s, this));
```
Two reasons to do this:
1. perf: only materialize messages if the log level is enabled
2. functions: using the `java.util.logging` mechanism for logging exceptions means that we actually get stack traces. Typically, the message provides little to no value without the stack trace. It's unfortunate that someone that didn't have experience writing java architected the JDBC driver as we know it, which is why we're going through all of these pains now lol. Ideally, we'd be using log4j like any sane, modern-day library, but here we are. I actually have a story to do this work we might be able to squeeze in the next month... https://ocient.atlassian.net/browse/DB-22051

Clean up these instances, if you happen to already be touching the surrounding code. Another really bad habit I see is using `Level.INFO` for every fricken log message which effectively eliminates any possibility of filtering logs at the logging config level, which is just so ridiculous. Messages like "Called XYX" are clear ccandidates for "TRACE" level logging (or "FINEST" in the `java.util.lgging` world).

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +				LOGGER.log(Level.WARNING, String.format("Failed sending set schema request to the server with exception %s with message %s", e.toString(), e.getMessage()));
we can probably kill this log message, just let the caller decide if they want to log the exception - they probably already do.

2023-04-19 21:45 UTC, jwilliams-ocient commented on src/main/java/com/ocient/util/Functions.java
> +    public static <T> Void noop(T t) { return null; }
I think you should add a new method for this as the no-return variant is surely used elsewhere in the codebase

2023-04-19 21:47 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +import io.netty.channel.VoidChannelPromise;
can probably delete this import, prefer `*Result.voidFuture()` or `StageSupport.voidFuture()` for a non-exceptional future

2023-04-19 21:48 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +					return completionStage;
Just saw your comment above, you are spot on 👍🏾

2023-04-19 22:04 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +					return completionStage;
I recommend decomposing this method into its logical parts:
1. Find _all_ known secondary interfaces paired with their relative index into the `secondaryInterfaces` list. Each secondary interface represents a database endpoint (annoying that we create obscure names for trivial, widely agreed upon concepts but w/e). If the client was connected to an endpoint at _some_ point in time (i.e. `secondaryIndex != -1`), the endpoint should be the first element in the returned list.
2. Iterate, asynchronously, over the list of known db endpoints, mapping each endpoint to a "connect-and-complete-handshake" routine that produces a `CompletionStage<SQLResult<Integer>>` that completes with a result representing the index of the endpoint in the `secondaryInterfaces` list upon success, else failure.
3. Your iterator should "find" the first endpoint that returns success, skipping endpoints that fail to connect.

I'd then recommend using the `AsyncIterator` interface to handle (2) and (3). See https://github.com/IBM/java-async-util/blob/0da9d9cb703ba3fd255c185d06aefa5f65de03eb/asyncutil/src/test/java/com/ibm/asyncutil/iteration/AsyncIteratorTest.java#L609-L615 for an example on how to use the "find" feature.

2023-04-21 13:56 UTC, jwilliams-ocient reviewed
Awesome, should merge this afternoon. 1 issue, the rest are nits :smile:

2023-04-21 13:56 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +					return StageSupport.completedStage(resultList);
(nit)

If you replace `Callable<T>` with `Supplier<T>` you can get rid of the try-catch block

2023-04-21 13:56 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +									LOGGER.log(Level.WARNING, e, () -> String.format("Failed sending set parameter request to the server after refresh with exception %s with message %s", e, e.getMessage()));
(nit)

Avoid printing the message which will shown up in the stack trace and include `this` which has a `toString()` method that will let us know which channel the error happened on.
```suggestion
									LOGGER.log(Level.WARNING, e, () -> String.format("Failed sending set parameter request to the server after refresh: %s", this));
```

There's more I want to do here w.r.t. contextual logging. There's  pattern referred to as `MDC` in logging utilities that allows you to define thread local variables to provide additional context to log messages implicitly i.e. a query ID used to prefix each message. The pattern is trickier to implement in a non-blocking world where code can run an any thread so I didn't do that, be we should consider doing something like that in the future.

2023-04-21 13:56 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			return SQLResult.voidResult();
(uber nit)

```suggestion
			return resOrEx.mapSuccess(Functions::noopBoxedVoid);
```

2023-04-21 13:56 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
>  		}
```suggestion
		SQLResult<Void> successOrEx = blockingGetSQLResult(setSchemaAsync(schema));
        if (successOrEx.isException()) {
            LOGGER.log(Level.WARNING, successOrEx.getException(), () -> String.format("Failed to update schema: %s", this));
            throw successOrEx.getException();
        }
```

2023-04-21 13:59 UTC, jwilliams-ocient reviewed
I like to run these two test fixtures when making connection-related changes to the driver:

```shell
bazel/run_ci_fixture.py quiesce_round_robin --config test_release -- --ocient_jdbc <path_to_your_custom_jar>
```
and
```shell
bazel/run_ci_fixture.py full_stack_connection_minimal --config test_release -- --ocient_jdbc <path_to_your_custom_jar>
```

Might be a good idea to run these before merging too.

2023-04-27 01:02 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +	private CompletionStage<List<SQLResult<Void>>> resendParameters()
So I get this error when simulating quiesce manually on your branch:

```
2023-04-27T12:50:13.071 [32] com.ocient.jdbc.XGStatement handleSendAndReceiveFailure WARNING: Error executing EXECUTE_QUERY request, failMode=RECV, channel=XGConnection[id=3, info=XGConnectionInfo[hint=STATEMENT, user='admin@system', pwd='*****', ip='localhost', portNum=4052, database='test', protocolVersion='7.1.0', tls=OFF, hints=[force=false, oneShotForce=false]], connected=true, socket=JavaNetOcientWireV1Transport [remote=localhost/127.0.0.1:4052, local=/127.0.0.1:38664]] 
java.sql.SQLException: 
	at com.ocient.jdbc.SQLStates.newGenericException(SQLStates.java:711)
	at com.ocient.jdbc.XGStatement.lambda$beginSendAndReceive$36(XGStatement.java:2373)
	at com.ocient.jdbc.XGConnection.lambda$sendRequest$125(XGConnection.java:5141)
	at com.ocient.util.CompletableFutures$SuccessResult.fold(CompletableFutures.java:226)
	at com.ocient.jdbc.XGConnection.lambda$sendRequest$126(XGConnection.java:5139)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.ocient.jdbc.XGStatement.lambda$beginSendAndReceive$36(XGStatement.java:2369)
	... 12 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at com.google.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:102)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2068)
	at com.ocient.jdbc.proto.ClientWireProtocol$ExecuteQueryResponse.<init>(ClientWireProtocol.java:38304)
	at com.ocient.jdbc.proto.ClientWireProtocol$ExecuteQueryResponse.<init>(ClientWireProtocol.java:38265)
	at com.ocient.jdbc.proto.ClientWireProtocol$ExecuteQueryResponse$1.parsePartialFrom(ClientWireProtocol.java:39373)
	at com.ocient.jdbc.proto.ClientWireProtocol$ExecuteQueryResponse$1.parsePartialFrom(ClientWireProtocol.java:39367)
	at com.ocient.jdbc.proto.ClientWireProtocol$ExecuteQueryResponse$Builder.mergeFrom(ClientWireProtocol.java:38921)
	at com.ocient.jdbc.proto.ClientWireProtocol$ExecuteQueryResponse$Builder.mergeFrom(ClientWireProtocol.java:38749)
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:420)
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:317)
	at com.google.protobuf.AbstractMessageLite$Builder.mergeFrom(AbstractMessageLite.java:260)
	at com.google.protobuf.AbstractMessage$Builder.mergeFrom(AbstractMessage.java:563)
	... 17 more
```

The "invalid tag" error means the application read garbage data off the socket. This is a little easier to debug because we know the protocol is simplex. The implication is that the client is sending requests concurrently. The "netty" impl has a proper guard for this (see the usage of the `AsyncLock` in that impl).

We have to make sure that the callers of this function are also waiting for this coroutine to complete before continuing.

2023-04-27 01:18 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +	private CompletionStage<List<SQLResult<Void>>> resendParameters()
It looks like `reset()` is at least one of the offenders

2023-05-02 19:04 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +					blockingGetSQLResult(reconnect());
hmm, I'm not sure we want to swallow reconnect failures, I think what you had before was right...

Or `blockingGetSQLResult(reconnect()).get();` which is just syntactic sugar for your `reconnectOrThrow()` helper method.

2023-05-02 19:16 UTC, jwilliams-ocient reviewed
It looks like we're swallowing some exceptions. Is that intentional?

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +			});
(nit)

```suggestion
			.thenApply(newStateOrEx -> newStateOrEx
			    .mapSuccess(newState -> {
			        this.sessionState = newState;
			        return (Void) null;
			    }));
```

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +				blockingGetSQLResult(reconnect());
I don't think we should swallow this exception
```suggestion
				blockingGetSQLResult(reconnect()).get();
```

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +				blockingGetSQLResult(reconnect());
```suggestion
				blockingGetSQLResult(reconnect()).get();
```

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +				blockingGetSQLResult(clientHandshakeFinalize());
```suggestion
				blockingGetSQLResult(clientHandshakeFinalize()).get();
```

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +				blockingGetSQLResult(reconnect());
```suggestion
				blockingGetSQLResult(reconnect()).get();
```

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +						blockingGetSQLResult(setPSO(false));
```suggestion
						blockingGetSQLResult(setPSO(false)).get();
```

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +						blockingGetSQLResult(setPSO(setPso.getAsLong()));
```suggestion
						blockingGetSQLResult(setPSO(setPso.getAsLong())).get();
```

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +						blockingGetSQLResult(setPSO(true));
```suggestion
						blockingGetSQLResult(setPSO(true)).get();
```

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> +				blockingGet(resendParameters());
```suggestion
				blockingGet(resendParameters()).get();
```

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> -							return runAsyncSafe_FIXME(conn::reconnect);
👍🏾

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGConnection.java
> -							return runAsyncSafe_FIXME(conn::reconnect)
👍🏾

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGResultSet.java
> +							.reconnect()
👍🏾 ah another silent merge conflict I missed 😢

2023-05-02 19:16 UTC, jwilliams-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> +		blockingGetSQLResult(conn.reconnect());
```suggestion
		blockingGetSQLResult(conn.reconnect()).get();
```

2023-05-04 15:08 UTC, merged