[DB-12845] output_next_query for explain and others
Xeograph/ocient_jdbc pull request #62
Opened 2020-09-13 22:45 UTC by tli-ocient

https://jira.ocient.com:8443/browse/DB-12845

Ugly diff, but really we are just adding an 
`if(outputfile){
print to output file;
}
else {
old code;
}
`

2020-09-13 22:49 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> -			ArrayList<Object> row = new ArrayList<>();
Is there a reason we were breaking up the string by new line characters and putting them into separate lines of the result set? It doesn't make a difference when its printed to stdout and is a bit uglier when printed to an output file.

2020-09-14 14:48 UTC, jasonar81 commented on src/main/java/com/ocient/jdbc/XGStatement.java
> -			ArrayList<Object> row = new ArrayList<>();
I believe we had to do it that way for dbeaver to work.

2020-09-14 14:49 UTC, jasonar81 requested changes
Can you bump the version in pom.xml and add a release note.

2020-09-14 15:26 UTC, tli-ocient commented on src/main/java/com/ocient/jdbc/XGStatement.java
> -			ArrayList<Object> row = new ArrayList<>();
It will be fine like this. They will go into one result cell. That makes it easier to copy and paste. Also Dbeaver has this value thing on the right side where you can view it easily.
![Screen Shot 2020-09-04 at 10 02 08 PM](https://user-images.githubusercontent.com/65177031/93105441-b31ec980-f674-11ea-9c88-4a1e7e3d5f5e.png)

2020-09-14 16:59 UTC, jasonar81 approved these changes

2020-09-14 16:59 UTC, merged